nilai = set({3,6,9,2,5,7})
print("suatu himpunan dengan anggota :")
print(nilai)
nilai.update({1,4,5,8,10})
print("himpunan setelah ditambah beberapa anggota baru")
print(nilai)
nilai.remove(1)
nilai.remove(3)
nilai.remove(4)
nilai.remove(5)
nilai.remove(7)
nilai.remove(8)
nilai.remove(10)
print("himpunan setelah dihapus beberapa anggotanya")
print(nilai)
